GET http://localhost:3000

### admin init

GET http://localhost:3000/api/admin/init

### admin create table

GET http://localhost:3000/api/admin/create-table
### admin create table

GET http://localhost:3000/api/admin/populate-posts-table

### Get all posts

GET http://localhost:3000/api/posts


### Get Single post

GET http://localhost:3000/api/posts/3

### Create post

POST http://localhost:3000/api/posts/
Content-Type: application/json

{
  "title": "Post from REST REST", 
  "author": "James Rest", 
  "date": "2000-01-02", 
  "body": "This is some meanigful content"
}
### Update post

PUT  http://localhost:3000/api/posts/3
Content-Type: application/json

{
  "title": "Update update", 
  "author": "James Rest 3000"
}

### Delete Single post

DELETE  http://localhost:3000/api/posts/2